---
repos:
  - repo: https://github.com/pycqa/isort
    rev: "5.11.5"
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black

  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.29.0"
    hooks:
      - id: yamllint

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: "v0.4.0"
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-alfred
          - flake8-breakpoint
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings
          - flake8-eradicate
          - flake8-logging-format
          - flake8-return

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
